export const route = {
  HOME: '/',
  DONATE: '/donate',
  DONATE_DETAIL: '/donate/detail',
  DONATE_LIST: '/donate/list',
  DONATE_NEW: '/donate/new',
  HELP: '/help',
  HELP_DETAIL: '/help/detail',
  HELP_LIST: '/help/list',
  HELP_NEW: '/help/new',
  CENSOR: '/censor',
  CENSOR_REGISTER: '/censor/register',
  CENSOR_LIST: '/censor/list',
  CENSOR_DETAIL: '/censor/detail',
  ARBITRATION: '/arbitration',
  ARBITRATION_LIST: '/arbitration/list',
  ARBITRATION_DETAIL: '/arbitration/detail',
  ARBITRATION_SUBMIT: '/arbitration/submit',
  SIGN_UP: '/user/sign-up',
};
